export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const GET_CONTENT = 'GET_CONTENT';
export const CHANGE_IFRAME_SOURCE = 'CHANGE_IFRAME_SOURCE';
